### PR TITLE
[RFC] Bootstrap the Cortex-M team

### PR DESCRIPTION
**Pull request by japaric**
As per RFC #136 this PR kickstarts the Cortex-M team

Note that the team composition is not final. The team is expected to grow over time. The mechanism
for joining a team is specified in RFC #136.

This is the team with most crates so it should have a large team to cope with the maintenance load.

active Cortex-M developers off the top of my head: would you be interested in helping maintain
these crates? @hannobraun @thejpster @therealprof @korken89

### CODE REVIEW

**Comment by korken89** [comment]
I would indeed be very interested!

**Comment by hannobraun** [comment]
I am generally interested, but my time is limited, and I'm currently prioritizing embedded-hal over the Cortex-M crates. If a certain level of activity is expected of members at all times, I should refrain from joining right now.

On the other hand, if it's okay with the other members that I won't be very active for the time being, I'd be happy to be a part of this team, and I'll pitch in as I can.

**Comment by adamgreig** [comment]
Not sure if you're looking for volunteers at this stage but I'd be interested in being a part of this team and am happy to commit time to these crates.

**Comment by japaric** [comment]
@korken89 @adamgreig Awesome! Thanks, you've been added to the team.

@hannobraun Thanks for considering joining. If we seem to be short staffed after the initial team is formed we'll reach out to you.

**Comment by therealprof** [comment]
Count me in.

**Pull request closed without merging**
