### PR TITLE
[RFC] Bootstrap the resources team

### PR DESCRIPTION
**Pull request by japaric**
As per RFC #136 this PR kickstarts the resources team

Note that the team composition is not final. The team is expected to grow over time. The mechanism
for joining a team is specified in RFC #136.

@jamesmunns approve this PR to accept my invitation to this team

@therealprof you have been doing a great job maintaining awesome embedded Rust; would you be
interested in joining this team to help review work on the books?

@andre-richter before, you expressed interest in joining this team; would you be interested in
joining to help review work on the books?

### CODE REVIEW

**Comment by andre-richter** [comment]
Yes I would still be very interested in doing reviews.

**Comment by jamesmunns** [comment]
@japaric do you want to include the [twitter account] in with the resources? I don't know where it would better fit, other than directly with `rust-embedded/wg.`

**Comment by japaric** [comment]
@jamesmunns @andre-richter awesome! Thanks.

@jamesmunns having twitter under the team sounds reasonable to me. What do you think, @andre-richter?

**Comment by andre-richter** [comment]
Thanks for adding! 😃

Regarding Twitter, I'd say depends on the scope of what it should cover. If all teams should be free to announce for example new versions of their tools themselves, then including it here instead of the top of might introduce an unessecary bottleneck?

**Comment by therealprof** [comment]
@japaric Yes, please.

**Comment by japaric** [comment]
@therealprof awesome, added.

@andre-richter so far we have been using the twitter account to tweet the newsletters, and have been retweeting help wanted stuff and project announcements. Now that there several projects under the rust-embedded org I think it makes sense to use the org twitter account to tweet announcements of new releases of those projects. I'm not sure if it would be a bottleneck or not, but if the resources team is taking long to respond a tweet request I think it's fine to tweet first from a personal account and then retweet it.

**Pull request closed without merging**
