### PR TITLE
[RFC] Bootstrap the MSP430 team

### PR DESCRIPTION
**Pull request by japaric**
As per RFC #136 this PR kickstarts the MSP430 team

r? @pftbest Let me know if you would prefer to maintain your projects as a separate org, or if you
would like to add some other person as a member as part of this PR.

cc @cr1901 @awygle

### CODE REVIEW

**Comment by pftbest** [comment]
@japaric can you please add @cr1901 to the team? I will also ask @awygle if they would like to join.

**Comment by japaric** [comment]
@pftbest done

**Comment by cr1901** [comment]
@japaric @pftbest What are your feelings on adding AT2XT under the projects section? It is feature complete and maintained, as in its _supposed_ to compile under the most recent nightly (that it doesn't currently is another matter:)...).

Being feature-complete, I would love for AT2XT to serve as an up-to-date (and deployed!) reference design of an example of how to write msp430 code (analogous to how quick start gives you a template for getting started)!

**Comment by japaric** [comment]
@cr1901 the projects under the rust-embedded org are supposed to be general purpose libraries and tools. Your project would be better fit for the curated list of projects (see #147).

**Comment by awygle** [comment]
@pftbest I am willing to join, thank you for considering me.

**Comment by japaric** [comment]
@pftbest the MSP430 team has been created. Once you have joined you should be able to transfer the msp430 repositories into the rust-embedded org. Let me know once you have transferred them and I'll set up the reviewer permissions and other stuff as described in https://github.com/rust-embedded/wg/pull/136#issuecomment-410936346. If you run into any trouble let me know!

**Pull request closed without merging**
