### PR TITLE
WIP: Add Embedded-WG Logo

### PR DESCRIPTION
**Pull request by jamesmunns**
Work in progress. Some items that still need to be done:

- [x] Get a PNG (with transparency) or SVG version of the logo from @Aaronepower
- [x] Receive a :+1: from trademark@rust-lang.org, as per the [copyright policy] of Rust (since we use the main rust logo as an element of our logo)
- [x] Write our usage policy, or at least refer to the Rust Lang [copyright policy]
- [x] Get a CC-BY sign off from @aaronepower

Here are some nice-to-have items, that would not block merging this PR:

- [x] Update any official account logo
    - [x] Github Repo
    - [x] Twitter Account
- [x] First sticker order :)
- [ ] Badge image for use in Embedded Rust repositories/crates

[copyright policy]: https://www.rust-lang.org/id-ID/legal.html

### CODE REVIEW

**Comment by jamesmunns** [comment]
Sent a message to trademark@rust-lang.org:

> Hello,
> 
> I'm James, from the Embedded Working Group. We are planning to start using a new logo that incorporates the Rust Gear Logo (see attached).
> 
> Our intended usage is:
> 
>  * As a logo for our "official" accounts/repos, including the Working Group Repo and our Twitter Account
>  * To print stickers with this logo
>  * To (maybe) print T-Shirts with this logo
> 
> 
> I wanted to get in touch before we officially started using the logo, just in case there are any concerns. We are tracking the PR for this logo on this GitHub issue, please feel free to reply to me by email, or comment directly on that issue if you have any comments.
> 
> Thanks!
> - James

I'll update here if they respond to me by email.

**Comment by andre-richter** [comment]
+ a smaller badge image to put on top of GitHub repos?

**Comment by jamesmunns** [comment]
Good call @andre-richter, I've broken up the to-do's into "must have" and "nice to have", and added that as a nice to have.

Also, I realized that @aaronepower already sent me an SVG of "White Text on Blue Chip on Transparent Background". I've added that plus an export of that to PNG (at 800x800px) to the repo. We may want to have another copy of this with the text and rust logo also transparent, but this is probably okay to get started :)

**Comment by jamesmunns** [comment]
Update: Received feedback from trademark@rust-lang.org- TL;DR, we're totally fine.

Paraphrased, the Embedded WG is an offical part of the Rust project, so we can use the logo as part of ours. We may allow companies to use the logo too, as long as they make it clear that their offerings are not an official part of Rust (for example displaying the logo as part of a Rust based BSP package).

I think we can probably just adopt the official Rust project usage terms by mentioning them in the top level README.

**Comment by jamesmunns** [comment]
Hey @aaronepower, would you mind confirming you are okay with your work being licensed under the CC By Attribution license? A reply here with something like the following would be great:

> I hereby license my logo design under the Creative Commons By Attribution v4 License

**Comment by jamesmunns** [comment]
@japaric OK to merge once Aaron provides his comment. Feel free to review now, no planned changes.

**Comment by Aaronepower** [comment]
I hereby license my logo design under the Creative Commons By Attribution v4 Licence.

**Pull request merged**
