### PR TITLE
[RFC] Bootstrap the RISCV team

### PR DESCRIPTION
**Pull request by japaric**
As per RFC #136 this PR kickstarts the RISCV team

r? @dvc94ch Let me know if you would prefer to maintain your projects as a separate org, or if you
would like to add some other person as a member as part of this PR.

### CODE REVIEW

**Comment by danc86** [comment]
I would be happy to help out... I have a Hifive1 and a Hifive Unleashed but my Rust still knowledge is still quite limited and I haven't been able to dedicate much time to working on it yet (hoping to change this in the next few months).

I'm not sure what exactly is involved in being on a Rust team like this though...

**Comment by dvc94ch** [comment]
> I'm not sure what exactly is involved in being on a Rust team like this though...

I'm not really sure either. I guess having more than one person having access to git repos is a good idea in case someone dies 😅

**Comment by dvc94ch** [comment]
@danc86 to be honest I'm in way over my head. People are taking this wg stuff very seriously and I feel like I'm not doing much even dough I'm a wg member. So I'm glad if I'm not the only one on the RISCV team, but that doesn't mean I expect anything more from you other than what you want to do.

**Comment by danc86** [comment]
Yeah it looks like all the relevant git repos are under the riscv-rust org which I have commit access to now. So you can put my name down. Having a bus factor of 2 is definitely better than 1. :-)

I'm assuming all the working group activities happen on Github issues/PRs, if so then I will certainly keep myself in the loop and send patches wherever I can.

If there is other stuff like IRC meetings or the like, I probably can't participate in those (if only because of my timezone which is UTC+10).

**Comment by danc86** [comment]
Oh we actually have a bus factor of 3 now since @bradjc also joined the riscv-rust Github org :-)

**Comment by dvc94ch** [comment]
@japaric would you like to add @danc86 and @bradjc to the team? they are both members of the riscv-rust org. I think for now we'll keep the repos there.

**Comment by bradjc** [comment]
I am reasonably familiar with embedded rust, but quite new to risc-v, so @danc86 we might be a good pair. I can help with the wg.

**Comment by japaric** [comment]
> would you like to add @danc86 and @bradjc to the team?

Sure!

@danc86 @bradjc welcome!

> I think for now we'll keep the repos there.

Having them under the rust-embedded org makes it easier for me to [track issues related to the 2018 edition](https://github.com/search?q=org%3Arust-embedded+is%3Aissue+is%3Aopen+milestone%3Arc1), but if you want to keep them in your org that's totally fine!

> I'm not sure what exactly is involved in being on a Rust team

The goals of the embedded WG teams are (a) increase the bus factor of the embedded crate ecosystem by having more people involved in their development / maintenance, and (b) have a communication channel through which users can report critical issues / bugs and request stabilization of core / std API that prevent some crate compiling on stable. The WG teams can also organize community wide efforts which we can announce in the newsletters under the "help wanted" section.

**Comment by japaric** [comment]
@dvc94ch I have created the RISCV team. I know you want to keep the repos in the riscv-rust org, but you might want to consider doing these changes (https://github.com/rust-embedded/wg/pull/136#issuecomment-410936346) to have a uniform contributor / reviews experience.

**Comment by dvc94ch** [comment]
@japaric We can move them to the rust-embedded org, I just haven't gotten around to it yet... I have access to rust-embedded now, so I can just transfer them?

**Comment by japaric** [comment]
@dvc94ch I don't see you in the list of members (https://github.com/orgs/rust-embedded/people). Did you access the invitation? (https://github.com/rust-embedded). Once you are a member of rust-embedded org you should be able to transfer the repos and assign them to the riscv team.

**Comment by dvc94ch** [comment]
@japaric Ups forgot to accept the invitation =P

**Comment by sekineh** [comment]
I’ll be attending RISC-V day Tokyo this week Oct 18.
Do you have current status of RISC-V support in Rust?

I suppose 
- To get RISC-V rust, you need to compile rust compiler yourself. (There are no precompiled RISC-V target installable by rustup)

Am I right?

**Comment by TeXitoi** [comment]
I think you just need to compile core using cargo, but the official rust compiler can cross compile for riscv-32. Only 32 bits microcontroller are supported.

**Comment by sekineh** [comment]
Thanks!

**Pull request closed without merging**
